### ISSUE TITLE
Docker image doesn't work

### ISSUE THREAD

**Issue by JamesDAdams** [wireapp/wire-webapp#12629]
## Your Account Type

- [X] Wire Personal Account
- [ ] [Wire Pro Account](https://wire.com/products/pro-secure-team-collaboration/)
- [ ] [Wire Enterprise Account](https://wire.com/products/enterprise-collaboration/)
- [ ] [Wire Red Account](https://wire.com/products/red-crisis-communication-software/)

## What steps will reproduce the problem?
Try to install wireapp on docker
## What is the expected behaviour?
the docker image doesn't start, and i have this on docker log : 

```
internal/modules/cjs/loader.js:818
throw err;
^

Error: Cannot find module '/dist/index.js'

at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
at Function.Module._load (internal/modules/cjs/loader.js:667:27)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
at internal/main/run_main_module.js:17:47 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}
```

## Which browser are you using?
Chrome

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

**Comment by JamesDAdams** [comment]
?
