### ISSUE TITLE
Error when run yarn start

### ISSUE THREAD

**Issue by hadi77makkawi** [wireapp/wire-webapp#2952]
When I run yarn start am getting the below error

Error: Command failed.
  Exit code: 6
  Command: sh
  Arguments: -c grunt
  Directory: _APPLICATION-DIRECTORY_
  Output:
  
      at ProcessTermError.MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:186:110)
      at new ProcessTermError (/usr/local/lib/node_modules/yarn/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:30281:17)
      at ChildProcess.emit (events.js:180:13)
      at maybeClose (internal/child_process.js:936:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

Node version => v8.10.0

yarn version => 1.5.1

**Comment by khjoony** [comment]
I'm getting the same thing.

prompt$ yarn start
 yarn run v1.5.1
 $ grunt
 sh: 1: grunt: Permission denied
 error An unexpected error occurred: "Command failed.
 Exit code: 127
 Command: sh
 Arguments: -c grunt
Directory: /home/khjoony/wire-webapp
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/khjoony/www/wire-webapp/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Node version => v8.6.0

yarn version => 1.5.1

**Comment by bennycode** [comment]
@hadi77makkawi & @khjoony: We recently updated the `yarn start` command (https://github.com/wireapp/wire-webapp/pull/3084). Can you please try again `yarn start` to see if it works now for you?

**Comment by gregor** [comment]
Closing this due to inactivity
